# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    baseURL: 'https://hyodae-seo.github.io/' # Website URL
    #url: https://hyodae-seo.github.io
    weight: 30
  - name: People
    url: people
    weight: 40
  - name: Publications
  # url: publication
    url: pubs
    weight: 50
  - name: Projects
    url: projects
    weight: 60
  - name: Teaching
    url: teaching
    weight: 70
  - name: SCOAR
    url: scoar
    weight: 80
  - name: Butterfly
    url: butterfly
    weight: 90
  - name: UC•AO
    url: https://www.soest.hawaii.edu/oceanography/uc-ao/
    weight: 100
  - name: OCN780
    url: ocn780_sp2025
    weight: 110
  - name: Calendar
    url: calendar
    weight: 120
